/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LFOutADC.h"
#include "LFOutPin_aliases.h"
#include "LFOutPin.h"
#include "redLight_aliases.h"
#include "redLight.h"
#include "errMonADC.h"
#include "errMonPin_aliases.h"
#include "errMonPin.h"
#include "aPin_aliases.h"
#include "aPin.h"
#include "bPin_aliases.h"
#include "bPin.h"
#include "fineDAC.h"
#include "fineDACOut_aliases.h"
#include "fineDACOut.h"
#include "switches.h"
#include "calibratePin_aliases.h"
#include "calibratePin.h"
#include "orangeLight_aliases.h"
#include "orangeLight.h"
#include "yellowLight_aliases.h"
#include "yellowLight.h"
#include "greenLight_aliases.h"
#include "greenLight.h"
#include "coarseDAC.h"
#include "coarseDACOut_aliases.h"
#include "coarseDACOut.h"
#include "setting8V_aliases.h"
#include "setting8V.h"
#include "setting22V_aliases.h"
#include "setting22V.h"
#include "setting28V_aliases.h"
#include "setting28V.h"
#include "blockLockPin_aliases.h"
#include "blockLockPin.h"
#include "sampleErrorMonitor_aliases.h"
#include "sampleErrorMonitor.h"
#include "SW_Tx_UART_1.h"
#include "SW_Tx_UART_1_PVT.h"
#include "tempTrigger_aliases.h"
#include "tempTrigger.h"
#include "LFOutADC_AMux.h"
#include "LFOutADC_Ext_CP_Clk.h"
#include "LFOutADC_IRQ.h"
#include "LFOutADC_theACLK.h"
#include "errMonADC_IRQ.h"
#include "errMonADC_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

